DROP KEYSPACE CrowdSourced;

CREATE KEYSPACE CrowdSourced;
USE CrowdSourced;

CREATE COLUMN FAMILY Tweets WITH COMPARATOR = 'UTF8Type';
CREATE COLUMN FAMILY Cafes WITH COMPARATOR = 'UTF8Type';
CREATE COLUMN FAMILY Suburbs WITH COMPARATOR = 'UTF8Type';
